<?php
 /****************************************************************************
  20150301  >> manual_general.php
  Proyecto: Obsevatorio Mario
  Código que define la matriz con el texto de ayuda general del aplicativo
 ******************************************************************************/
	
	$manual['tit'] = 'Guía General de Usuario' ;
	$manual['tex'] = '
Este manual presenta la funcionalidad el aplicativo MaxInmuebles, el cual sirve para hacer seguimiento del sector inmobiliario en Bogotá y para identificar oportunidades de compra de la empresa Renovaciones Urbanas SAS. 
Para cada una de las opciones del aplicativo el usuario podrá encontrar un botón “Guia de Usuario” donde encontrará una explicación detallada de la funcionalidad así como una explicación de los campos de cada formulario. Para acceder a la explicación se deberá presionar sobre el botón y se desplegará una ventana emergente con las instrucciones. 
En esta introducción se hará un resumen de las principales funcionalidades y cómo se integran entre sí. La explicación está dividida en módulos de acuerdo con la funcionalidad en cada uno de ellos. Los módulos del aplicativo se dividen en:
Captura de información del mercado:
1.	El módulo tiene la opción de captura manual y captura automática. Para la captura manual se debe seguir la ruta <b>Operación>Captura Manual</b> en el menú. Acá se ingresan los datos iniciales para el registro e identificación de un inmueble. 
2.	Para la captura automática se deben seguir una serie de pasos que se describen más adelante. Debido a que el proceso involucra la consulta de información en portales externos, se sigue un proceso dividido en etapas donde el usuario tiene la libertad de acomodar la cantidad de registros a procesar y por tanto el tiempo de ejecución. A mayor cantidad, mayor tiempo de ejecución.
2.1.	Antes de comenzar el proceso es necesario depurar la memoria para eliminar información de capturas anteriores.  Esto se logra mediante la ruta <b>Operación>Captura Automática>Reset Captura</b>.
2.2.	Posteriormente se identifica el segmento de inmuebles a ser consultados, definiendo sector, rango de precios y antigüedad. Esto se logra mediante la ruta <b>Operación>Captura Automática>Descarga MC</b>. Las consultas realizadas mediante este procedimiento se archivan en el disco del sistema con un código específico a cada tipo de consulta. El código está optimizado para trabajar sobre inmuebles tipo ‘Apartamento’ ubicados en las zonas Norte, Noroccidente, Occidente y Chapinero de Bogotá. 
2.3.	Una vez se han generado las consultas anteriores se puede ejecutar la consulta para descargar los datos Nivel 1 de cada inmueble. Esta funcionalidad se activa mediante la ruta <b>Operación>Captura Automática>Datos N1 estándar y Operación>Captura Automática>Datos N1 otros</b>. La primera opción permite procesar automáticamente los archivos estandarizados del sistema los cuales comprenden:
2.3.1.	Zonas: Norte, Noroccidente, Chapinero, Occidente
2.3.2.	Antigüedad: Para Estrenar, 0 a 10 años (0 a 5 años y 5 a 10 años), 10 a 20 años, Más de 20 años.
La segunda opción se debe utilizar cuando se realizan consultas no estandarizadas. Por ejemplo inmuebles en otro sector ó nuevos rangos de precios. En este caso es necesario que el usuario verifique el nombre del archivo generado en la etapa anterior, para ingresarlo al aplicativo en el formulario.
Este segundo nivel de consultas se va acumulando en la memoria del sistema, por lo que es recomendable no repetir una misma consulta sin primero haber realizado un Reset del sistema (opción 2.1). De la misma forma es recomendable no acumular más de 2000 registros en esta etapa ya que puede perjudicar el desempeño de los siguientes pasos.
2.4.	Una vez se han generado las consultas anteriores el sistema está preparado para hacer la búsqueda detallada sobre la página externa de los Datos Nivel 2 (incluyen precio, número de habitaciones, teléfono de contacto, etc). Este proceso toma mayor tiempo dependiendo del tiempo de respuesta del portal externo y del número de registros a procesar.  Para hacer la consulta externa se debe seguir la ruta <b>Operación>Captura Automática>Datos N2</b>. Al finalizar el proceso se presenta un resumen de las transacciones realizadas y los datos obtenidos.
2.4.1. Ocasionalmente el proceso de consulta no alcanza a terminar en el tiempo límite. En este caso se debe observar cuál fue el último registro procesado y volver a utilizar la funcionalidad pero incluyendo en la casilla del formulario el número del registro final que fue procesado.
2.5.	Una vez culminado el proceso anterior, es necesario ingresar la información en la Base de Datos del sistema. Para esto se utiliza la ruta <b>Operación>Captura Automática>Insertar a BD</b>. Al finalizar la ejecución se presenta un resumen del proceso y los cambios importantes en la información del sistema.
2.6.	La última opción permite consultar los datos Nivel 3 de los registros. En este caso la consulta sólo se realiza para los inmuebles que están en los barrios EN SEGUIMIENTO (esta clasificación se explicará más adelante). Esta funcionalidad se activa mediante la ruta <b>Operación>Captura Automática>Datos N1 estándar</b> y <b>Operación>Datos N3 (seg)</b>.
3.	Una vez finalizada la consulta anterior, los registros ya se han ingresado a la Base de Datos del sistema. En este punto se deben ejecutar algunos procesos adicionales para depurar la calidad de la información capturada en el portal externo. En primer lugar se identifican los inmuebles con precios ó áreas fuera de lo normal. Esta funcionalidad se ejecuta mediante la ruta <b>Operación>Depuración>Limpieza datos</b>.
3.1.	Una vez realizada la limpieza anterior es recomendable revisar aquellos registros que el sistema ha identificado como potenciales GEMELOS (los GEMELOS son registros diferentes pero que en el fondo identifican el mismo inmueble). Para depurar los posibles GEMELOS se debe seguir la ruta <b>Operación>Depuración>Revisar Gemelos</b>.
3.2.	Una vez depurada la información anterior se procede a realizar el recálculo de indicadores fundamentales (e.g. el Precio por Metro Cuadrado ) de los registros de la Base de Datos. Esta funcionalidad se ejecuta mediante la ruta <b>Operación>Depuración>Indicadores x Inmueble</b>.
3.3.	Por último, se requiere monitorear los inmuebles que se consideran VIGENTES (la VIGENCIA de un inmueble es el periodo entre la fecha_inicio y la fecha_fin. Por defecto, los inmuebles pierden vigencia 15 días después de la fecha de inicio o de la última vez que se cargó información relacionada con el inmueble) la opción ruta <b>Operación>Depuración>Prolongar Inmuebles</b> permite revisar los inmuebles que pierden vigencia en la fecha indicada y prolongar aquellos que se considere necesario.
Presentación de Estadísticas:
4.	Las opciones bajo la ruta <b>Operación>Tablas></b> permiten visualizar la información del sistema bajo diferentes perspectivas. El usuario puede escoger la opción que más se acomode a sus necesidades. Toda la información está agrupada de acuerdo con los barrios definidos en el sistema.
4.2.	La ruta <b>Operación>Tablas>Datos mínimos</b> presenta información similar a la desplegada en la opción anterior. La diferencia es que en este caso se filtran los datos así que sólo se despliegan los inmuebles en barrios donde existen datos para diferentes rangos de antigüedad y estratos, de tal forma que existan criterios mínimos para hacer comparaciones relativas.
4.3.	La ruta <b>Operación>Tablas>Seleccionar</b> presenta los mismo registros que la ruta anterior ordenados de una manera diferente. Esta opción incluye la columna adicional “valor_rel” la cual presenta un ponderado de los precios de inmuebles usados vs. Inmuebles nuevos. La tabla se ordena de acuerda con esta columna donde los menores valores indican mayores oportunidades de valorización.
4.4.	La ruta <b>Operación>Tablas>Comparativo MC</b> presenta los mismo registros incluido en la opción 4.2. En este caso se incluyen columnas adicionales con datos de la primera  franja de tiempo definida en las tablas estandarizadas de metrocuadrado.com, es decir la franja de 2 a 8 años. Adicionalmente en cada columna incluye el diferencial entre el precio promedio del mercado y el valor de mercado de la franja de nuevo. 
4.5.	La ruta <b>Operación>Tablas>Por zonas</b> presenta estadísticas acumulativas de promedio, mínimo y máximo acumulativos en tres tablas. La primera esta agrupada por sectores, la segunda está agrupada por zonas y la tercera está agrupada por estratos. Esta presentación es muy útil para identificar irregularidades en los datos ingresados a la Base de Datos del sistema.
4.1.	La ruta <b>Operación>Tablas>Todos</b> presenta un listado general de TODOS los inmuebles que están vigentes en el sistema. Esta opción también incluye tablas que no contiene formato específico y por lo tanto son útiles para descargar información en aplicativos como hojas de cálculo.
5.	Las opciones bajo la ruta <b>Operación>Intertemporal</b> presentan estadísticas comparativas entre dos cortes diferentes en el tiempo. La recomendación es que los cortes históricos se realicen con una periodicidad mínima de 1 mes.
5.1.	La ruta <b>Operación>Intertemporal>Comparativo Mensual</b> presenta la comparación de los precios promedios (valor por omisión) y de otros 5 estadísticos de los barrios. Los resultados se presentan ordenados acorde con la magnitud del cambio entre los dos cortes.
5.2.	 La ruta <b>Operación>Intertemporal>Rotación</b> presenta una estimativo de la cantidad de inmuebles que se mantienen vigentes a través los dos cortes así como los inmuebles nuevos y los que pierden vigencia entre los dos cortes. Estos datos son apropiados para jerarquizar los niveles de rotación en cada barrio.
Identificación de Oportunidades de Negocio:
6.	Las opciones bajo la ruta Operación>Seguimiento</b> incluyen funcionalidades que permiten hacer seguimiento de oportunidades de negocio identificados en los registros de la Base de Datos del sistema. 
6.1.	La ruta <b>Operación> Seguimiento >Ofertas Día</b> presenta un listado de los inmuebles que tienen un precio de venta que parece indicar un mayor margen de utilidad al compararlos contra los precios de mercado en el estrato y barrio del inmueble. Los registros se presentan ordenados por margen  de utilidad.
6.2.	La ruta <b>Operación> Seguimiento >Inmuebles</b> presenta un listado de los inmuebles que se han marcado  EN SEGUIMIENTO en la Base de Datos. Los inmuebles que se encuentran marcado para seguimiento es aquellos donde se ha diligenciado la MATRIZ DE EVALUACIÓN o PRESUPUESTO.
6.3.	La ruta <b>Operación> Seguimiento >Barrios</b> presenta un listado de los barrios que se han marcado para  EN SEGUIMIENTO. Al comienzo del listado se presenta el id_barrio de los barrios marcados y a continuación todos los demás barrios sin marcar ordenados alfabéticamente. La funcionalidad sirve para marcar y desmarcar los barrios. A los barrios que son seleccionados en este pantalla es a los que se les realiza la consulta Nivel 3 en el proceso de Captura de información e Mercado. Se sugiere que se marquen menos de 8 barrios para optimizar la velocidad de ejecución del proceso de captura de datos externos.
Administración:
7.	Las opciones bajo la ruta <b>Administración></b>  incluyen funcionalidades que permiten conocer información del estado de la base de datos del sistema. También incluyen funcionalidades para poblar las talas de parametrización del sistema y los cortes de tiempo históricos.
7.1.	La ruta <b>Administración > Conteo Fechas</b> presenta un listado de la cantidad de registros ingresados al sistema en cada fecha, así como sus fechas de vigencia. Sirve para monitorear los resultados del proceso de captura externa en una fecha específica.
7.2.	La ruta <b>Administración > Corte Mensual</b> permite al usuario definir una fecha para realizar un corte mensual de estadísticas. Esta fecha de corte mensual se verá reflejada en los reportes generados en las opciones 5.1. y 5.2. del sistema.  Debido a que la información se genera con los datos disponibles en el punto histórico escogido, esta opción se debe ejecutar en los días siguientes al periodo de corte escogido, si se ejecuta nuevamente o se ejecuta después se corre el riesgo de que la cifras pierdan precisión ya que los datos habrán cambiado con el paso del tiempo.
7.3.	La ruta <b>Administración > Generar idBarrios</b> permite al usuario inicializar la tabla de barrios de la Base de Datos (t_barrio), de forma tal que cada barrio sea asignado a un identificador único. La fuente de alimentación de datos de barrio es la tabla taux_barrio, la cual debe haber sido previamente poblada con los campos relevantes de barrio, sector y zona de las tablas estandarizadas de metrocuadrado.com.	
	' ;
	
	echo VentanaHelp( $manual ) . "<br>" ;
?>